# -*- coding: utf-8 -*-
"""examine

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16r5zqDZhs6Q27-8gj6nwX1vLMr-YxGGq
"""

import numpy as np
#training_data=np.load("training_data.npy")
print(training_data[1][0:30][0:17])
print(training_data[1:][0:30][0:17])