# -*- coding: utf-8 -*-
"""GenerateConfusionMatrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fqKM5Oirz16s7FbZzYbkwLp-vTiG6q25
"""

def printConfusionMatrix(model):
  predicted_labels=model.predict(my_testing_generator)
  predicted_labels=np.argmax(predicted_labels)
  testing_labels=np.argmax(testing_labels)
  confusion_matrix=confusion_matrix(testing_labels,predicted_labels)
  print(cm)